/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Form_Management;

import View.ThongBao;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import service.impl.SystemServiceImpl;

/**
 *
 * @author quanc
 */
public class CaiDat_Form extends javax.swing.JPanel {

    public CaiDat_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelBourder1 = new View.DesignComponent.JPanelBourder();
        txtSoLuongLowerThan = new View.DesignComponent.TextField();
        txtEmail = new View.DesignComponent.TextField();
        txtSDT = new View.DesignComponent.TextField();
        btnInBaoCao1 = new View.ButtonDesign.Button();
        cbTrangThai = new View.DesignComponent.Combobox();
        cbTrangThai1 = new View.DesignComponent.Combobox();
        cbTrangThai2 = new View.DesignComponent.Combobox();

        setBackground(new java.awt.Color(11, 20, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Management Book - Cài Đặt Báo Cáo");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Settings System");

        jPanelBourder1.setBackground(new java.awt.Color(17, 28, 68));

        txtSoLuongLowerThan.setBackground(new java.awt.Color(17, 28, 68));
        txtSoLuongLowerThan.setForeground(new java.awt.Color(255, 255, 255));
        txtSoLuongLowerThan.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSoLuongLowerThan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtSoLuongLowerThan.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtSoLuongLowerThan.setLabelText("Thông Báo khi số lượng nhỏ hơn");
        txtSoLuongLowerThan.setLineColor(new java.awt.Color(255, 255, 255));
        txtSoLuongLowerThan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongLowerThanActionPerformed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(17, 28, 68));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtEmail.setLabelText("Email");
        txtEmail.setLineColor(new java.awt.Color(255, 255, 255));

        txtSDT.setBackground(new java.awt.Color(17, 28, 68));
        txtSDT.setForeground(new java.awt.Color(255, 255, 255));
        txtSDT.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSDT.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtSDT.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtSDT.setLabelText("Số Điện Thoại");
        txtSDT.setLineColor(new java.awt.Color(255, 255, 255));

        btnInBaoCao1.setBackground(new java.awt.Color(19, 29, 243));
        btnInBaoCao1.setBorder(javax.swing.BorderFactory.createEmptyBorder(-3, 1, 1, 1));
        btnInBaoCao1.setForeground(new java.awt.Color(255, 255, 255));
        btnInBaoCao1.setText("Lưu Thiết Lập");
        btnInBaoCao1.setFocusable(false);
        btnInBaoCao1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnInBaoCao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInBaoCao1ActionPerformed(evt);
            }
        });

        cbTrangThai.setBackground(new java.awt.Color(17, 28, 68));
        cbTrangThai.setForeground(new java.awt.Color(255, 255, 255));
        cbTrangThai.setMaximumRowCount(10);
        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bật", "Tắt" }));
        cbTrangThai.setSelectedIndex(1);
        cbTrangThai.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cbTrangThai.setLabeText("Trạng Thái");
        cbTrangThai.setLineColor(new java.awt.Color(255, 255, 255));
        cbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrangThaiActionPerformed(evt);
            }
        });

        cbTrangThai1.setBackground(new java.awt.Color(17, 28, 68));
        cbTrangThai1.setForeground(new java.awt.Color(255, 255, 255));
        cbTrangThai1.setMaximumRowCount(10);
        cbTrangThai1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gửi SMS", "Gửi Email", "Kết Hợp Cả 2" }));
        cbTrangThai1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cbTrangThai1.setLabeText("Hình Thức");
        cbTrangThai1.setLineColor(new java.awt.Color(255, 255, 255));
        cbTrangThai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrangThai1ActionPerformed(evt);
            }
        });

        cbTrangThai2.setBackground(new java.awt.Color(17, 28, 68));
        cbTrangThai2.setForeground(new java.awt.Color(255, 255, 255));
        cbTrangThai2.setMaximumRowCount(10);
        cbTrangThai2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thông báo ngay lập tức", "Thông báo vào 8h tối mỗi ngày", "Kết hợp cả 2" }));
        cbTrangThai2.setSelectedIndex(1);
        cbTrangThai2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cbTrangThai2.setLabeText("Thông Báo");
        cbTrangThai2.setLineColor(new java.awt.Color(255, 255, 255));
        cbTrangThai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrangThai2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBourder1Layout = new javax.swing.GroupLayout(jPanelBourder1);
        jPanelBourder1.setLayout(jPanelBourder1Layout);
        jPanelBourder1Layout.setHorizontalGroup(
            jPanelBourder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBourder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBourder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoLuongLowerThan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTrangThai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cbTrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBourder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInBaoCao1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBourder1Layout.setVerticalGroup(
            jPanelBourder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBourder1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelBourder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoLuongLowerThan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(cbTrangThai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInBaoCao1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jPanelBourder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBourder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void getDatainFile() {
        FileInputStream fileInputStream = null;
        boolean TurnOnorOff = false;
        int QuantityLowerThan = 9999;
        int hinhThuc = -1;
        String sdt = "-";
        String email = "-";
        int typeSend = -1;

        try {
            String url = "settingsSend.txt";
            // Đọc dữ liệu từ File với Scanner
            fileInputStream = new FileInputStream(url);
            Scanner scanner = new Scanner(fileInputStream);
            int i = 0;
            List<String> list = new ArrayList<>();
            try {
                while (scanner.hasNextLine()) {
                    list.add(scanner.nextLine());
                }
            } finally {
                try {
                    scanner.close();
                    fileInputStream.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
            if (list.get(0).equals("true")) {
                TurnOnorOff = true;
            }
            QuantityLowerThan = Integer.parseInt(list.get(1));
            hinhThuc = Integer.parseInt(list.get(2));
            sdt = list.get(3);
            email = list.get(4);
            typeSend = Integer.parseInt(list.get(5));
            setData(TurnOnorOff, QuantityLowerThan, email, "0" + sdt, hinhThuc, typeSend);
            System.out.println(TurnOnorOff + " - " + QuantityLowerThan + " - " + hinhThuc + " - " + sdt + " - " + email);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SystemServiceImpl.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(SystemServiceImpl.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void setData(boolean toogle, int quantity, String email, String sdt, int hinhThuc, int typeSend) {
        if (toogle == true) {
            cbTrangThai.setSelectedIndex(0);
        } else {
            cbTrangThai.setSelectedIndex(1);
        }
        txtSoLuongLowerThan.setText("" + quantity);
        txtEmail.setText(email);
        txtSDT.setText(sdt);
        if (hinhThuc == 1) {
            cbTrangThai1.setSelectedIndex(0);
        } else if (hinhThuc == 2) {
            cbTrangThai1.setSelectedIndex(1);
        } else {
            cbTrangThai1.setSelectedIndex(2);
        }
        if (typeSend == 1) {
            cbTrangThai2.setSelectedIndex(0);
        } else if (typeSend == 2) {
            cbTrangThai2.setSelectedIndex(1);
        } else {
            cbTrangThai2.setSelectedIndex(2);
        }

    }
    private void btnInBaoCao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInBaoCao1ActionPerformed
        String Quatity, Email, SDT;
        boolean Toogle = false;
        int hinhThuc = -1;
        int typeSend = -1;
        Quatity = txtSoLuongLowerThan.getText().trim();
        Email = txtEmail.getText().trim();
        SDT = txtSDT.getText().trim();
        String sdtRegex = "";
        sdtRegex = SDT.substring(1, SDT.length());
        hinhThuc = cbTrangThai1.getSelectedIndex() + 1;
        if (cbTrangThai.getSelectedItem().toString().equals("Bật")) {
            Toogle = true;
        }
        int quanti = 9999;
        try {
            quanti = Integer.parseInt(Quatity);
        } catch (Exception e) {
            ThongBao.showNoti_Error(this, "Vui lòng nhập số lượng là chữ và >0");
            return;
        }
        typeSend = cbTrangThai2.getSelectedIndex() + 1;
        SystemServiceImpl.setDataSettings(Toogle, quanti, hinhThuc, sdtRegex, Email, typeSend);
        ThongBao.showNoti_Succes(this, "Lưu Thành Công");
    }//GEN-LAST:event_btnInBaoCao1ActionPerformed

    private void cbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTrangThaiActionPerformed

    private void txtSoLuongLowerThanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongLowerThanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongLowerThanActionPerformed

    private void cbTrangThai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrangThai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTrangThai1ActionPerformed

    private void cbTrangThai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrangThai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTrangThai2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.ButtonDesign.Button btnInBaoCao1;
    private javax.swing.ButtonGroup buttonGroup1;
    private View.DesignComponent.Combobox cbTrangThai;
    private View.DesignComponent.Combobox cbTrangThai1;
    private View.DesignComponent.Combobox cbTrangThai2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private View.DesignComponent.JPanelBourder jPanelBourder1;
    private javax.swing.JSeparator jSeparator1;
    private View.DesignComponent.TextField txtEmail;
    private View.DesignComponent.TextField txtSDT;
    private View.DesignComponent.TextField txtSoLuongLowerThan;
    // End of variables declaration//GEN-END:variables
}
