/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Form_Management;

import View.ButtonDesign.Button;
import View.ThongBao;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.NhaXuatBan;
import model.Sach;
import model.ViTri;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.SachService;
import service.impl.SachServiceImpl;
//s

/**
 *
 * @author quanc
 */
public class Sach_Form extends javax.swing.JPanel {

    private final SachService _sachService = new SachServiceImpl();

    private final int _pageSize = 10;
    private int _currentPage = 1;
    private int _totalPage;
    private boolean searcher = false;

    private List<Sach> _lstSach;
    private List<Button> listBtn = new ArrayList<>();
    private String _currentDirectory = "";

    public Sach_Form() {
        initComponents();
//        String columns[] = {"Nhà xuất bản", "Vị trí", "Mã", "Tên", "Số lượng", "Số trang", "Giá nhập", "Giá bán", "Trạng thái", "Hình"};

        table1.setBackground(Color.WHITE);
        this.table1.setRowHeight(59);
        this.table1.setBackground(Color.white);
        loadAll();
//        showTarget(1);

    }

    public void loadAll() {
        loadTable(0, _pageSize);
        setPageLabel(false);
    }

    private void setPageLabel(boolean searching) {
        if (searching == false) {
            int result = _sachService.countAllSach();
            if (result % _pageSize == 0) {
                _totalPage = result / _pageSize;
            } else {
                _totalPage = (result / _pageSize) + 1;
            }
            lblPage.setText("Viewing " + ((_currentPage - 1) * _pageSize + 1) + " - " + ((_currentPage - 1) * _pageSize + _pageSize) + " of " + result);
        } else {
            int result = _lstSach.size();
            if (result % _pageSize == 0) {
                _totalPage = result / _pageSize;
            } else {
                _totalPage = result / _pageSize + 1;
            }
            lblPage.setText("Viewing " + ((_currentPage - 1) * _pageSize + 1) + " - " + ((_currentPage - 1) * _pageSize + _pageSize) + " of " + result);
        }

    }

    private void setLabelPage() {
        lblPage.setText("Viewing " + ((_currentPage - 1) * _pageSize + 1) + " - " + ((_currentPage - 1) * _pageSize + _pageSize) + " of " + _sachService.countAllSach());
    }

    public JButton getListbtn() {
        return this.btnTaoSP1;
    }

    public JTable getJTable() {
        return this.table1;
    }

    public void loadTable(int position, int pageSize) {
        _lstSach = _sachService.getList(position, pageSize);
        DefaultTableModel dtm = (DefaultTableModel) table1.getModel();
        dtm.setRowCount(0);
        for (Sach sach : _lstSach) {
            this.table1.addRow(sach.toDataRow());
        }
    }

    public void loadTableSearch(List<Sach> lst, int position, int pageSize) {
        _lstSach = lst;
        DefaultTableModel dtm = (DefaultTableModel) table1.getModel();
        dtm.setRowCount(0);
        for (int i = position * 10; i < position * 10 + 10; i++) {
            if (_lstSach.size() <= i) {
                return;
            }
            dtm.addRow(_lstSach.get(i).toDataRow());
        }
    }

    public void setColorButtonSelected(int index) {
        for (Button btn : listBtn) {
            btn.setBackground(Color.WHITE);
            btn.setForeground(Color.BLACK);
        }
        listBtn.get(index).setBackground(new Color(31, 31, 111));
        listBtn.get(index).setForeground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagePanel = new javax.swing.JPanel();
        jPanelBourder1 = new View.DesignComponent.JPanelBourder();
        txtSearch = new View.DesignComponent.TextField();
        jLabel2 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        lblPage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSearch = new View.ButtonDesign.Button();
        btnImport = new View.ButtonDesign.Button();
        btnExport = new View.ButtonDesign.Button();
        btnTaoSP1 = new View.ButtonDesign.Button();
        jPanelBourder3 = new View.DesignComponent.JPanelBourder();
        jPanelBourder2 = new View.DesignComponent.JPanelBourder();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new View.DesignComponent.Table();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(11, 20, 55));
        setPreferredSize(new java.awt.Dimension(1373, 978));

        pagePanel.setBackground(new java.awt.Color(29, 32, 57));
        pagePanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanelBourder1.setBackground(new java.awt.Color(17, 28, 68));

        txtSearch.setBackground(new java.awt.Color(17, 28, 68));
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSearch.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtSearch.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtSearch.setLabelText("Tìm kiếm theo mã, tên, ...");
        txtSearch.setLineColor(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 143, 222));
        jLabel2.setText("List of Book");

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image_Hub/icons8_previous_40px.png"))); // NOI18N
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreviousMouseClicked(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image_Hub/icons8_next_40px.png"))); // NOI18N
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        lblPage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblPage.setForeground(new java.awt.Color(255, 255, 255));
        lblPage.setText("Viewing 1-10 of 36");
        lblPage.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btnSearch.setBackground(new java.awt.Color(31, 31, 111));
        btnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(-3, 1, 1, 1));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image_Hub/icons8_add_35px.png"))); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.setFocusable(false);
        btnSearch.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBourder1Layout = new javax.swing.GroupLayout(jPanelBourder1);
        jPanelBourder1.setLayout(jPanelBourder1Layout);
        jPanelBourder1Layout.setHorizontalGroup(
            jPanelBourder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBourder1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious)
                .addGap(6, 6, 6)
                .addComponent(btnNext))
        );
        jPanelBourder1Layout.setVerticalGroup(
            jPanelBourder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBourder1Layout.createSequentialGroup()
                .addGroup(jPanelBourder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBourder1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(jPanelBourder1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBourder1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBourder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelBourder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBourder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBourder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnImport.setBackground(new java.awt.Color(31, 31, 111));
        btnImport.setBorder(javax.swing.BorderFactory.createEmptyBorder(-3, 1, 1, 1));
        btnImport.setForeground(new java.awt.Color(255, 255, 255));
        btnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image_Hub/icons8_new_copy_35px.png"))); // NOI18N
        btnImport.setText("Import Excel");
        btnImport.setFocusable(false);
        btnImport.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnExport.setBackground(new java.awt.Color(31, 31, 111));
        btnExport.setBorder(javax.swing.BorderFactory.createEmptyBorder(-3, 1, 1, 1));
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image_Hub/icons8_microsoft_excel_35px.png"))); // NOI18N
        btnExport.setText("Export Excel");
        btnExport.setFocusable(false);
        btnExport.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnTaoSP1.setBackground(new java.awt.Color(31, 31, 111));
        btnTaoSP1.setBorder(javax.swing.BorderFactory.createEmptyBorder(-3, 1, 1, 1));
        btnTaoSP1.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoSP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image_Hub/icons8_add_35px.png"))); // NOI18N
        btnTaoSP1.setText("Tạo Sản Phẩm");
        btnTaoSP1.setFocusable(false);
        btnTaoSP1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnTaoSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoSP1ActionPerformed(evt);
            }
        });

        jPanelBourder3.setBackground(new java.awt.Color(47, 55, 90));

        jPanelBourder2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBourder2.setMaximumSize(new java.awt.Dimension(1333, 32767));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1333, 32767));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 395));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NXB1", "VT1", "S1", "Đắc Nhân Tâm", "15", "200", "20000", "30000", "Đang Bán", "None"},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nhà Xuất Bản", "Vị Trí", "Mã", "Tên", "Số Lượng", "Số Trang", "Giá Nhập", "Giá Bán", "Trạng thái", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        table1.setMaximumSize(new java.awt.Dimension(1333, 200));
        table1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout jPanelBourder2Layout = new javax.swing.GroupLayout(jPanelBourder2);
        jPanelBourder2.setLayout(jPanelBourder2Layout);
        jPanelBourder2Layout.setHorizontalGroup(
            jPanelBourder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelBourder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBourder2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1333, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelBourder2Layout.setVerticalGroup(
            jPanelBourder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
            .addGroup(jPanelBourder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBourder2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanelBourder3Layout = new javax.swing.GroupLayout(jPanelBourder3);
        jPanelBourder3.setLayout(jPanelBourder3Layout);
        jPanelBourder3Layout.setHorizontalGroup(
            jPanelBourder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBourder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBourder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBourder3Layout.setVerticalGroup(
            jPanelBourder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBourder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBourder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Management Book - Quản Lý Sách");

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(1330, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(557, 557, 557)
                        .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnTaoSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelBourder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBourder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBourder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanelBourder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoSP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaoSP1ActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        exportExcel();
    }//GEN-LAST:event_btnExportActionPerformed

    private void exportExcel() {

        JFileChooser fileChooser = new JFileChooser(_currentDirectory);
        fileChooser.setPreferredSize(new Dimension(800, 600));
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel", "xlsx"));
        fileChooser.showSaveDialog(this);
        File file = fileChooser.getSelectedFile();
        if (file == null) {
            return;
        }
        if (!file.exists()) {
            try {
                file.mkdirs();
                file = new File(file.getAbsolutePath() + ".xlsx");
                file.createNewFile();
                _currentDirectory = file.getParent();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("book");
        String[] header = new String[]{"Id", "IdNXB", "IdViTri", "Mã sách", "Tên sách", "Số lượng", "Số trang", "Giá nhập", "Giá bán", "Trạng thái", "BarCode", "Mô tả"};

        int rowCount = 0;
        Row row = sheet.createRow(rowCount++);
        int columnCount = 0;
        for (String string : header) {
            Cell cell = row.createCell(columnCount++);
            cell.setCellValue(string);
        }

        for (Sach sach : _lstSach) {
            row = sheet.createRow(rowCount++);
            columnCount = 0;
            for (String string : sach.getStringArray()) {
                Cell cell = row.createCell(columnCount++);
                cell.setCellValue(string);
            }

        }

        try ( FileOutputStream outputStream = new FileOutputStream(file)) {
            workbook.write(outputStream);
            ThongBao.showNoti_Succes(this, "Ghi file thành công");
        } catch (FileNotFoundException ex) {
            ThongBao.showNoti_Error(this, "File đang được mở ở một nơi khác không thể ghi đè");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        List<Sach> lst = importExcel();
        boolean insertStatus = _sachService.insertSach(lst);
        if(insertStatus) {
            ThongBao.showNoti_Succes(this, "Import file thành công");
        } else {
            ThongBao.showNoti_Error(this, "Import file thất bại. Lỗi bất định");
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private List<Sach> importExcel() {
        List<Sach> lst = new ArrayList<>();
        JFileChooser fileChooser = new JFileChooser(_currentDirectory);
        fileChooser.setPreferredSize(new Dimension(800, 600));
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel", "xlsx"));
        int result = fileChooser.showDialog(this, "Chọn excel");
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            FileInputStream fis = null;
            try {
                fis = new FileInputStream(file);

                XSSFWorkbook wb = new XSSFWorkbook(fis);
                XSSFSheet sheet = wb.getSheetAt(0);
                Iterator<Row> itr = sheet.iterator();

                itr.next();
                while (itr.hasNext()) {
                    Sach sach = new Sach();
                    Row row = itr.next();
                    Iterator<Cell> cellItr = row.iterator();

                    Cell cell = cellItr.next();
                    sach.setId(cell.getStringCellValue());

                    cell = cellItr.next();
                    NhaXuatBan nxb = new NhaXuatBan(cell.getStringCellValue(), null, null, null);
                    sach.setNhaXuatBan(nxb);

                    cell = cellItr.next();
                    ViTri vitri = new ViTri(cell.getStringCellValue(), null, null);
                    sach.setViTri(vitri);

                    cell = cellItr.next();
                    sach.setMa(cell.getStringCellValue());

                    cell = cellItr.next();
                    sach.setTen(cell.getStringCellValue());

                    cell = cellItr.next();
                    switch (cell.getCellType()) {
                        case Cell.CELL_TYPE_STRING:
                            sach.setSoLuong(Integer.parseInt(cell.getStringCellValue()));
                            break;
                        default:
                            sach.setSoLuong((int) cell.getNumericCellValue());
                    }

                    cell = cellItr.next();
                    sach.setSoTrang(Integer.parseInt(cell.getStringCellValue()));

                    cell = cellItr.next();
                    sach.setGiaNhap(BigDecimal.valueOf(Double.parseDouble(cell.getStringCellValue().replaceAll(",", ""))));

                    cell = cellItr.next();
                    sach.setGiaBan(BigDecimal.valueOf(Double.parseDouble(cell.getStringCellValue().replaceAll(",", ""))));

                    cell = cellItr.next();
                    sach.setTrangThai(Integer.parseInt(cell.getStringCellValue()));

                    cell = cellItr.next();
                    sach.setBarCode(cell.getStringCellValue());

                    try {
                        cell = cellItr.next();
                        sach.setMoTa(cell.getStringCellValue());
                    } catch (NoSuchElementException e) {

                    }

                    lst.add(sach);

                }

                fis.close();
            } catch (FileNotFoundException ex) {
                ThongBao.showNoti_Error(this, "Lỗi. Không tìm thấy file");
            } catch (IOException ex) {
                ex.printStackTrace();
            }

        }
        return lst;
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText();
        if (keyword.isBlank()) {
            setPageLabel(false);
            loadTable(0, _pageSize);
            searcher = false;
            return;
        }
        searcher = true;
        _currentPage = 1;
        loadTableSearch(_sachService.getListByKeyword(keyword), 0, _pageSize);
        setPageLabel(true);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseClicked
        if (_currentPage == 1) {
            return;
        }
        if (!searcher) {
            _currentPage = _currentPage--;
            loadTable(_currentPage - 1, _pageSize);
            setLabelPage();
        } else {
            loadTableSearch(_lstSach, _currentPage - 1, _pageSize);
            _currentPage = _currentPage--;
            setLabelPage();
        }
    }//GEN-LAST:event_btnPreviousMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        if (_currentPage == _totalPage) {
            return;
        }
        if (!searcher) {
            _currentPage = _currentPage++;
            loadTable(_currentPage - 1, _pageSize);
            setLabelPage();
        } else {
            _currentPage = _currentPage++;
            loadTableSearch(_lstSach, _currentPage - 1, _pageSize);
            setLabelPage();
        }
    }//GEN-LAST:event_btnNextMouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.ButtonDesign.Button btnExport;
    private View.ButtonDesign.Button btnImport;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnPrevious;
    private View.ButtonDesign.Button btnSearch;
    private View.ButtonDesign.Button btnTaoSP1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private View.DesignComponent.JPanelBourder jPanelBourder1;
    private View.DesignComponent.JPanelBourder jPanelBourder2;
    private View.DesignComponent.JPanelBourder jPanelBourder3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPage;
    private javax.swing.JPanel pagePanel;
    private View.DesignComponent.Table table1;
    private View.DesignComponent.TextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
