/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package View;

import javax.swing.JDialog;
import model.NhanVien;
import util.Auth;

/**
 *
 * @author quanc
 */
public class SplassScreen_Form extends java.awt.Dialog {

    ManagementBookForm mng = null;

    public SplassScreen_Form(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
//        getContentPane().setBackground(new Color(221, 221, 221));
//        //  To disable key Alt+F4 to close dialog

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pro = new View.ProgressBarCustom();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(11, 20, 55));
        jPanel2.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 380, 220, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Team 1 ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 190, 211, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("fbook version 1.0.0");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(150, 160, 211, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Book Sales Manager");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(150, 120, 380, 41);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Instructors : PhongTT35");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(150, 220, 211, 25);

        pro.setBorder(null);
        pro.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(pro);
        pro.setBounds(0, 410, 690, 10);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Coppy right @2022 Team 1");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(500, 380, 180, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\quanc\\Downloads\\SplitShire-03692-1800x1200-uai-1800x1012 (1).jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 690, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {

                    doTask("Connect To Database ...", 10);
                    doTask("loading form/management_book ...", 20);
                    doTask("loading ser./iser/implser ...", 22);
                    doTask("loading ser./iser/image2323. ...", 35);
                    doTask("loading ser./util/hibernate ...", 45);
                    doTask("loading ser./iser/kxxw/x34.pd ...", 55);
                    doTask("loading ser./iser/kbog.prc./3933/ ....", 77);
                    doTask("loading ser./iser/30497.png./d ...", 80);
                    doTask("loading ser./content./23", 90);
                    do {
                        doTask("loading ser./poe09/.938", 100);
                    } while (mng == null);
                    doTask("Done ...", 100);
                    dispose();
                    if (Auth.getNhanVien().getChucVu().getMa().equalsIgnoreCase("Nhân viên")) {
                        mng.btnTest.doClick();
                    }
                    mng.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(ManagementBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(ManagementBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(ManagementBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(ManagementBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                mng = new ManagementBookForm();

            }
        }).start();
    }//GEN-LAST:event_formWindowOpened
    private void doTask(String taskName, int progress) throws Exception {
        jLabel1.setText(taskName);
        Thread.sleep(550); //  For Test
        pro.setValue(progress);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SplassScreen_Form dialog = new SplassScreen_Form(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private View.ProgressBarCustom pro;
    // End of variables declaration//GEN-END:variables
}
